### PR TITLE
Issue/jperf 769 migrate ci to GitHub actions

### PR DESCRIPTION
**Pull request by mzyromski-atlassian**
Working CI on my fork: https://github.com/mzyromski-atlassian/ssh-ubuntu/actions/runs/1611492643

### CODE REVIEW

**Review by pczuj — APPROVED** [review]

**Review by dagguh — APPROVED** [review]

**Comment by mzyromski-atlassian** [comment]
The CI is now red, but it [fails](https://github.com/mzyromski-atlassian/ssh-ubuntu/actions/runs/1611593705) with the same timeout problem on my fork with the same commit too (while it was [green](https://github.com/mzyromski-atlassian/ssh-ubuntu/actions/runs/1611492643) moments before that), hence I suspect it might be related to current AWS infra issues. I'll check later and verify.

**Comment by pczuj** [comment]
@mzyromski-atlassian AWS seems to experience some outages right now. Maybe this is related.

https://downdetector.com/status/aws-amazon-web-services/

**Comment by mzyromski-atlassian** [comment]
@pczuj, yes, that's exactly what I suspect to be the culprit.

**Comment by mzyromski-atlassian** [comment]
The CI is green now: https://github.com/atlassian/ssh-ubuntu/actions/runs/1648810573

**Pull request merged**
