### PR TITLE
Migrate to artifact publish token

### PR DESCRIPTION
**Pull request by rinconjc**
Artifactory secrets are being deprecated.

Please review and merge this change to use the new artifact publish token.

### CODE REVIEW

**Review by pczuj — APPROVED** [review]

**Comment by pczuj** [comment]
After merge the build failed with https://ecosystem.atlassian.net/browse/JPERF-812. I'm fixing the flakiness in #22

**Comment by pczuj** [comment]
After merging the #22 I tried to release the module, but it failed: https://github.com/atlassian/ssh-ubuntu/runs/7088589178?check_suite_focus=true

I don't think this failure is caused by artifactory authentication and I'm not sure how to fix it right now.

I will ensure a JPERF issue exists for that and leave the problem for later to be fixed.

**Comment by pczuj** [comment]
I believe this is the issue: https://ecosystem.atlassian.net/browse/JPERF-791

**Comment by rinconjc** [comment]
I think the docker image name needs to include the registry: docker-public.packages.atlassian.com/...

Not sure how this was working before. Anyway, I'll dig further tomorrow.

**Pull request merged**
